name: "zodgame"

on:
  schedule:
    - cron: "18 1 * * *"  # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:

env:
  # auto merge from y1ndan/genshin-impact-helper, default: false
  ALLOW_MERGE: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:

      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main


      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-300 -n 1)

      - name: Run sign
        run: |
          python -m pip install --upgrade pip
          pip install requests
          ls -a
          python3 ./zodgame/zodgame.py '${{ secrets.COOKIE }}'