name: "Auto Sign"

on:
  schedule:
    - cron: '00 23 * * *'  # scheduled at 07:30 (UTC+8) everyday
    - cron: '0 */7 * * *'  # scheduled at every 7 hours
  workflow_dispatch:

env:
  ALLOW_MERGE: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:

      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main


      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 2-5 -n 1)
          
      - name: Run southplus
        if: github.event.schedule == '00 23 * * *' || github.event_name != 'schedule'
        run: |
          echo "Run southplus..."
          python -m pip install --upgrade pip
          pip install requests --quiet
          python3 ./checkin/southplus.py '${{ secrets.SOUTHPLUS_COOKIE }}'

      - name: Run feiyue
        if: github.event.schedule == '00 23 * * *' || github.event_name != 'schedule'
        run: |
          echo "Run feiyue..."
          python -m pip install --upgrade pip
          pip install requests parsel --quiet
          python3 ./checkin/feiyue.py '${{ secrets.FEIYUE_COOKIE }}'
          
      - name: Run tsdm
        if: github.event.schedule == '0 */7 * * *' || github.event_name != 'schedule'
        run: |
          echo "Run tsdm..."
          python -m pip install --upgrade pip
          pip install requests parsel --quiet
          python3 ./checkin/tsdm.py '${{ secrets.TSDM_COOKIE }}'

      - name: Run telegram
        if: github.event.schedule == '00 23 * * *' || github.event_name != 'schedule'
        run: |
          echo "Run telegram..."
          python -m pip install --upgrade pip
          pip install requests telethon --quiet
          cd ./checkin/telegram
          python telegram.py '${{ secrets.TELEGRAM_API_HASH }}'
          cd -

      - name: Run smzdm
        #if: github.event.schedule == '00 23 * * *' || github.event_name != 'schedule'
        if: github.event_name != 'schedule'
        run: |
          echo "Run smzdm..."
          python -m pip install --upgrade pip
          pip install requests prettytable --quiet
          python3 ./checkin/smzdm.py '${{ secrets.SMZDM_COOKIE }}'

      - name: Run heybox
        #if: github.event.schedule == '00 23 * * *' || github.event_name != 'schedule'
        if: github.event_name != 'schedule'
        run: |
          echo "Run heybox..."
          python -m pip install --upgrade pip
          pip install requests --quiet
          python3 ./checkin/heybox.py '${{ secrets.HEYBOX_COOKIE }}'

      - name: Run karaoke
        #if: github.event.schedule == '00 23 * * *' || github.event_name != 'schedule'
        if: github.event_name != 'schedule'
        run: |
          echo "Run karaoke..."
          python -m pip install --upgrade pip
          pip install requests --quiet
          python3 ./checkin/karaoke.py '${{ secrets.KARAOKE_COOKIE }}'

      - name: Run tieba
        if: github.event.schedule == '00 23 * * *' || github.event_name != 'schedule'
        run: |
          echo "Run tieba..."
          python -m pip install --upgrade pip
          pip install requests --quiet
          python3 ./checkin/tieba.py '${{ secrets.TIEBA_COOKIE }}'

      - name: Run zodgame
        if: github.event.schedule == '00 23 * * *' || github.event_name != 'schedule'
        run: |
          echo "Run zodgame..."
          python -m pip install --upgrade pip
          pip install requests --quiet
          python3 ./checkin/zodgame.py '${{ secrets.ZODGAME_COOKIE }}'

      - name: Run jd
        if: github.event.schedule == '00 23 * * *' || github.event_name != 'schedule'
        run: |
          echo "Run jd..."
          python -m pip install --upgrade pip
          pip install requests --quiet
          python3 ./checkin/jd.py '${{ secrets.JD_COOKIE }}'

      - name: Run ibizhi
        if: github.event.schedule == '00 23 * * *' || github.event_name != 'schedule'
        run: |
          echo "Run ibizhi..."
          python -m pip install --upgrade pip
          pip install requests js2py numpy --quiet
          python3 ./checkin/ibizhi.py
          git config --global user.email "issizhe@outlook.com"
          git config --global user.name "thekips"
          git add .
          git commit -m "update wallpaper.txt"
          git push
