name: "zodgame"

on:
  schedule:
    - cron: "30 23 * * *"  # scheduled at 07:30 (UTC+8) everyday
    - cron: "* */7 * * *"  # scheduled at every 7 hours
  workflow_dispatch:

env:
  # auto merge from y1ndan/genshin-impact-helper, default: false
  ALLOW_MERGE: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:

      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main


      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 2-60 -n 1)

      - name: Run zodgame
        if: github.event.schedule == '30 23 * * *'
        run: |
          echo "Run zodgame..."
          python -m pip install --upgrade pip
          pip install requests
          python3 ./checkin/zodgame.py '${{ secrets.ZODGAME_COOKIE }}'

      - name: Run tsdm
        if: github.event.schedule == '* */7 * * *'
        run: |
          echo "Run tsdm..."
          python -m pip install --upgrade pip
          pip install requests parsel
          python3 ./checkin/tsdm.py '${{ secrets.TSDM_COOKIE }}'